### ISSUE TITLE
There is a bug when bacth_size  ！=1 .

### ISSUE THREAD

**Issue by XiaokunFeng** [wudongming97/OnlineRefer#2]
Thanks for your great work! 
I find that the default value of batch_size is 1 in your release code.
But when I set other values to batch_size (such  as 2, 4), it doesn't work...
The relevant wrong information is :

  File "/home/fxk/python_proj/tracking_proj/OnlineRefer/models/ops/modules/ms_deform_attn.py", line 99, in forward
    sampling_offsets = self.sampling_offsets(query).view(N, Len_q, self.n_heads, self.n_levels, self.n_points, 2)
RuntimeError: shape '[2, 5, 8, 4, 4, 2]' is invalid for input of size 1280

**Comment by wudongming97** [comment]
Sorry. My code does not support batch size > 1 now.

**Comment by XiaokunFeng** [comment]
Ok, thanks.
