### ISSUE TITLE
mian_joint.py is not avaliable.

### ISSUE THREAD

**Issue by yahooo-m** [wudongming97/OnlineRefer#4]
Hi, could you tell me whether you only train the model in ytvos?

**Comment by wudongming97** [comment]
We use the model pre-trained on refcoco (the model is downloaded from ReferFormer) to train the model in ytvos.

**Comment by yahooo-m** [comment]
Thanks.
So, you just finetune the model in the video datasets.
Have you tried the joint training?

**Comment by wudongming97** [comment]
Sorry. I have not tried joint training because the image-based dataset refcoco cannot support online training.
